[build]
  base = "" # Leave empty or set to your subdirectory like "backend"
  command = "npm install && npm run build"
  publish = "" # Leave empty for serverless apps
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
